import { useState, useEffect } from "react";
import Head from "next/head";
import Image from "next/image";
import Chart from "chart.js/auto";
import Select from "../components/Select";
import Card from "../components/Card";
import BarChart from "../components/BarChart";
import API from "../components/util/API";
import styles from "../styles/Home.module.css";

export default function Home() {
  const [accounts, setAccounts] = useState([{}]);
  const [accountId, setAccountId] = useState("");
  const [accountStats, setAccountStats] = useState({});
  const [accountCostsHistory, setAccountCostsHistory] = useState([{}]);

  /**
   * On the first render, call the API
   * to get the list of accounts and
   * set the first one as the main
   */
  useEffect(() => {
    API.getAccounts().then((data) => {
      setAccounts(data);
      setAccountId(data[0].id);
    });
  }, []);

  /**
   * Once accountId has a new value,
   * Fetches the account stats and
   * costs history
   */
  useEffect(() => {
    API.getAccountStats(accountId).then((data) => setAccountStats(data));
    API.getAccountCostsHistory(accountId).then((data) =>
      setAccountCostsHistory(data)
    );
  }, [accountId]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Oraculi - Frontend Challenge</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Select your account</h1>
        <Select accounts={accounts} setAccountId={setAccountId} />

        <Card type="bill" title="Bill" accountStats={accountStats} />
        <Card type="servers" title="Servers" accountStats={accountStats} />
        <Card type="regions" title="Regions" accountStats={accountStats} />
        <Card type="alarms" title="Alarms" accountStats={accountStats} />

        <BarChart accountCostsHistory={accountCostsHistory} />
      </main>
    </div>
  );
}
